name: publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0-9 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: publish
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libssl-dev pkg-config librust-openssl-sys-dev
          git config --global user.name 'ajou-hack-bot'
          git config --global user.email 'bot@ajou-hack.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ajou-hack/notice-rss
          cargo build --release
          LAST_INDEX=$(cat ./last_index)
          XML=$(./target/release/notice-rss $LAST_INDEX xml 2> /dev/null)
          MD=$(./target/release/notice-rss $LAST_INDEX md 2> /dev/null)
          CM=$(./target/release/notice-rss $LAST_INDEX cm 2> /dev/null)
          if [ -z "$XML" ] || [ -z "$MD" ] || [ -z "$CM" ]; then
          echo "new notices not found"
          exit 0
          fi
          echo $XML > rss.xml
          echo -e $MD > README.md
          cat ./target/release/last_index > ./last_index
          git add -A
          git commit -m "$CM"
          git push origin master

